FROM pytorch/pytorch:2.7.0-cuda11.8-cudnn9-runtime

# Avoid interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
        wget \
        # These are common dependencies used by ffmpeg/install_ffmpeg.sh
        libass-dev \
        libfreetype6-dev \
        libsdl2-dev \
        libtool \
        libva-dev \
        libvdpau-dev \
        libvorbis-dev \
        libxcb1-dev \
        libxcb-shm0-dev \
        libxcb-xfixes0-dev \
        texinfo \
        zlib1g-dev \
        nasm \
        yasm \
        libx264-dev \
        libx265-dev \
        libnuma-dev \
        libvpx-dev \
        libmp3lame-dev \
        libopus-dev \
        libgl1 \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender1 \
        vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/
COPY . .

# cv_reader CLI imports cv2, install headless version suitable for containers
RUN pip install --no-cache-dir opencv-python-headless

# Execute install.sh to install ffmpeg / cv_reader etc
RUN bash install.sh

# Default working directory
WORKDIR /workspace

# Start bash by default for debugging
CMD ["bash"]